"""《精简写作》目录种子方法（48 条）。

来源：用户提供的目录层面整理（user_supplied_toc_summary），未独立核对书目与正文。
方法名称为用户整理表述，非书中逐字原文；`why_effective` / `when_to_use` / `boundaries`
是 Finch 的阅读效果假设与适应说明，不归因于作者。`mini_exercise` 是 Finch 为用户需求
设计的建议（finch_adaptation），也不归因于作者。

稳定 ID 为 EP-CW-001 至 EP-CW-048，保留章节、原编号、方法类型、维度、证据状态、
来源、适用场景、限制与 Finch 练习建议。导入方式见 ``ExpressionMethodService.seed_cw48``。
"""

SOURCE_NOTE = (
    "目录层面整理（user_supplied_toc_summary），未独立核对正文；方法名称为用户整理表述。"
    "来源线索：豆瓣阅读 https://read.douban.com/ebook/619741533/；"
    "当当电子书 https://e.dangdang.com/products/1901365379.html；"
    "得到电子书 https://www.dedao.cn/ebook/detail?id=lxaVvndNG6D4kgLJ2OKxqVMmE1zXPwV2lZAwAdjyQeYR75vbaBnr9ol8pZERLg1m"
)

# 每条：id, title, chapter, method_type（technique/training/scenario）, dimension,
# when_to_use, why_effective（阅读效果假设）, boundaries, mini_exercise（Finch 适应建议）,
# executable（「待补充」= False）。
CW48_SEED: list[dict] = [
    {
        "id": "EP-CW-001",
        "title": "围绕要点写",
        "chapter": "提炼要点",
        "method_type": "technique",
        "dimension": "主题",
        "when_to_use": "一段需要围绕单一中心展开时",
        "why_effective": "读者能判断每句是否推进同一中心",
        "boundaries": "可能让文字变干；不适用于需要悬念或情绪铺陈的段落",
        "mini_exercise": "为段落写一句中心意思，检查每句与其关系",
        "executable": True,
    },
    {
        "id": "EP-CW-002",
        "title": "一页提炼一行",
        "chapter": "提炼要点",
        "method_type": "training",
        "dimension": "提炼",
        "when_to_use": "材料过载、需要抓住主干时",
        "why_effective": "压缩迫使区分主次",
        "boundaries": "可能丢失限定与细节；不替代原文记录",
        "mini_exercise": "从一页材料中写一行主要信息",
        "executable": True,
    },
    {
        "id": "EP-CW-003",
        "title": "三种方案选最佳",
        "chapter": "提炼要点",
        "method_type": "technique",
        "dimension": "比较",
        "when_to_use": "一个素材有多种切入方式时",
        "why_effective": "比较暴露每种切入的效果与素材要求",
        "boundaries": "不是随机抽三条；每种须适合当次素材",
        "mini_exercise": "比较三种切入点的效果与素材要求，由用户选择",
        "executable": True,
    },
    {
        "id": "EP-CW-004",
        "title": "用40字概括",
        "chapter": "提炼要点",
        "method_type": "training",
        "dimension": "压缩",
        "when_to_use": "表达冗长、抓不住核心时",
        "why_effective": "字数上限逼出取舍",
        "boundaries": "不是所有会话的必经步骤；可能损失必要的不确定性",
        "mini_exercise": "尝试用约40字表达核心意思，再检查遗漏",
        "executable": True,
    },
    {
        "id": "EP-CW-005",
        "title": "借助对话框表达情绪",
        "chapter": "提炼要点",
        "method_type": "technique",
        "dimension": "情绪",
        "when_to_use": "",
        "why_effective": "",
        "boundaries": "不猜测对话框的具体用法",
        "mini_exercise": "待补充：不猜测对话框的具体用法",
        "executable": False,
    },
    {
        "id": "EP-CW-006",
        "title": "用网络翻译辅助检查可理解性",
        "chapter": "提炼要点",
        "method_type": "training",
        "dimension": "清晰",
        "when_to_use": "",
        "why_effective": "",
        "boundaries": "不把译文或回译稳定性当作理解证明",
        "mini_exercise": "待补充：不把译文或回译稳定性当作理解证明",
        "executable": False,
    },
    {
        "id": "EP-CW-007",
        "title": "考虑跨语言、跨文化的读者",
        "chapter": "提炼要点",
        "method_type": "scenario",
        "dimension": "读者",
        "when_to_use": "读者可能不共享你的背景时",
        "why_effective": "减少依赖读者不了解的背景",
        "boundaries": "不是把所有背景都补全；只补会妨碍理解的",
        "mini_exercise": "检查是否依赖目标读者不了解的背景",
        "executable": True,
    },
    {
        "id": "EP-CW-008",
        "title": "尝试给事物命名",
        "chapter": "提炼要点",
        "method_type": "technique",
        "dimension": "命名",
        "when_to_use": "反复描述同一个观察、缺少一个称呼时",
        "why_effective": "一个贴切的名字让讨论可指称",
        "boundaries": "命名须能一句话定义；不造空泛新词",
        "mini_exercise": "为观察拟一个名称，并用一句话定义，检查是否贴切",
        "executable": True,
    },
    {
        "id": "EP-CW-009",
        "title": "尝试用钢笔书写",
        "chapter": "提炼要点",
        "method_type": "training",
        "dimension": "书写",
        "when_to_use": "想换一种书写节奏时（离线）",
        "why_effective": "手写放慢速度，改变构思节奏",
        "boundaries": "可选离线练习，不设为线上流程前提",
        "mini_exercise": "可选离线练习，不设为线上流程前提",
        "executable": True,
    },
    {
        "id": "EP-CW-010",
        "title": "设置行文路标",
        "chapter": "建立框架",
        "method_type": "technique",
        "dimension": "结构",
        "when_to_use": "转折或推进位置读者容易迷路时",
        "why_effective": "路标让结构可预期",
        "boundaries": "路标过密会打断节奏；只加必要的",
        "mini_exercise": "为一个转折或推进位置添加简短提示",
        "executable": True,
    },
    {
        "id": "EP-CW-011",
        "title": "先连贯写完，再果断删减",
        "chapter": "建立框架",
        "method_type": "technique",
        "dimension": "修订",
        "when_to_use": "边写边改导致卡住时",
        "why_effective": "先完成再删，避免过早自我审查",
        "boundaries": "删减须以目标为准，不删关键限定",
        "mini_exercise": "先完成一个段落，再删除与目标无关的句子",
        "executable": True,
    },
    {
        "id": "EP-CW-012",
        "title": "借鉴《桃太郎》的开篇方式",
        "chapter": "建立框架",
        "method_type": "technique",
        "dimension": "开头",
        "when_to_use": "",
        "why_effective": "",
        "boundaries": "不杜撰其开篇步骤或结构",
        "mini_exercise": "待补充：不杜撰其开篇步骤或结构",
        "executable": False,
    },
    {
        "id": "EP-CW-013",
        "title": "先交代结论",
        "chapter": "建立框架",
        "method_type": "technique",
        "dimension": "结构",
        "when_to_use": "读者想先知道判断时",
        "why_effective": "结论前置降低理解成本",
        "boundaries": "可能减少悬念或背景铺垫；比较后再定",
        "mini_exercise": "尝试结论前置，并比较是否减少悬念或背景",
        "executable": True,
    },
    {
        "id": "EP-CW-014",
        "title": "用带有强烈感受的表达引发兴趣",
        "chapter": "建立框架",
        "method_type": "technique",
        "dimension": "语气",
        "when_to_use": "开头需要抓住读者时",
        "why_effective": "真实感受比中性陈述更引人读下去",
        "boundaries": "不夸大事实或伪造情绪；须是真实感受",
        "mini_exercise": "选择一个真实感受表达，不夸大事实或伪造情绪",
        "executable": True,
    },
    {
        "id": "EP-CW-015",
        "title": "按读者的需要安排信息顺序",
        "chapter": "建立框架",
        "method_type": "technique",
        "dimension": "结构",
        "when_to_use": "读者最需要知道的事不靠前时",
        "why_effective": "把读者最需要的先给，减少翻找",
        "boundaries": "「最需要」由当次读者定，不是作者觉得重要的",
        "mini_exercise": "先列读者最需要知道的事，再调整段落顺序",
        "executable": True,
    },
    {
        "id": "EP-CW-016",
        "title": "围绕读者能获得什么构思文章",
        "chapter": "建立框架",
        "method_type": "scenario",
        "dimension": "读者",
        "when_to_use": "确定文章价值主张时",
        "why_effective": "明确读者获益，避免自说自话",
        "boundaries": "不夸大收益；只写能兑现的理解或行动",
        "mini_exercise": "说明读者会获得的理解或行动帮助",
        "executable": True,
    },
    {
        "id": "EP-CW-017",
        "title": "检查容易出错的语法和敬语",
        "chapter": "建立框架",
        "method_type": "technique",
        "dimension": "措辞",
        "when_to_use": "面向正式对象或涉及敬语时",
        "why_effective": "减少低级错误带来的信任损失",
        "boundaries": "按实际语言与关系检查，不照搬日语敬语规则",
        "mini_exercise": "按实际语言与关系检查，不照搬日语敬语规则",
        "executable": True,
    },
    {
        "id": "EP-CW-018",
        "title": "选择小学生也能理解的词汇",
        "chapter": "建立框架",
        "method_type": "technique",
        "dimension": "清晰",
        "when_to_use": "术语堆砌、读者可能读不懂时",
        "why_effective": "日常词降低理解门槛",
        "boundaries": "换词须不丢精确性；关键术语保留并解释",
        "mini_exercise": "选一个术语改用日常词，检查是否丢失精确性",
        "executable": True,
    },
    {
        "id": "EP-CW-019",
        "title": "用自己的定义体现独特性",
        "chapter": "建立框架",
        "method_type": "technique",
        "dimension": "定义",
        "when_to_use": "用到通行词但想表达不同判断时",
        "why_effective": "个人定义划出自己的区分",
        "boundaries": "须与通行定义明确区分，不能混用",
        "mini_exercise": "写出个人使用的定义，并与通行定义区分",
        "executable": True,
    },
    {
        "id": "EP-CW-020",
        "title": "尝试边散步边构思",
        "chapter": "建立框架",
        "method_type": "training",
        "dimension": "构思",
        "when_to_use": "坐着想不出、需要换环境时（离线）",
        "why_effective": "走动改变状态，可能带出新的联想",
        "boundaries": "可选离线构思，返回后记录关键点",
        "mini_exercise": "可选离线构思，返回后记录关键点",
        "executable": True,
    },
    {
        "id": "EP-CW-021",
        "title": "像写情书一样考虑接收者",
        "chapter": "打磨表达",
        "method_type": "scenario",
        "dimension": "读者",
        "when_to_use": "写给一个具体的人、需要贴合对方时",
        "why_effective": "有具体接收者，措辞更有对象感",
        "boundaries": "不是真的情书口吻；只检查信息与接收者的相关度",
        "mini_exercise": "选定一个具体接收者，检查哪些信息与其有关",
        "executable": True,
    },
    {
        "id": "EP-CW-022",
        "title": "用自然、融洽的对话式表达传递情绪",
        "chapter": "打磨表达",
        "method_type": "technique",
        "dimension": "语气",
        "when_to_use": "文字读起来生硬、缺少情绪时",
        "why_effective": "对话式口吻更自然，情绪更容易传递",
        "boundaries": "须保留真实感受，不装出没有的情绪",
        "mini_exercise": "把一句改成自然说话的口吻，保留真实感受",
        "executable": True,
    },
    {
        "id": "EP-CW-023",
        "title": "减少含糊的委婉表达",
        "chapter": "打磨表达",
        "method_type": "technique",
        "dimension": "语气",
        "when_to_use": "委婉词遮蔽了立场时",
        "why_effective": "直说让立场可被回应",
        "boundaries": "保留必要的不确定性，不是一律直说",
        "mini_exercise": "检查一个委婉词是否遮蔽立场，保留必要的不确定性",
        "executable": True,
    },
    {
        "id": "EP-CW-024",
        "title": "给句子编号，辅助检查文章",
        "chapter": "打磨表达",
        "method_type": "training",
        "dimension": "检查",
        "when_to_use": "",
        "why_effective": "",
        "boundaries": "不猜测作者的编号检查程序",
        "mini_exercise": "待补充：不猜测作者的编号检查程序",
        "executable": False,
    },
    {
        "id": "EP-CW-025",
        "title": "用居中排列辅助审视文字",
        "chapter": "打磨表达",
        "method_type": "training",
        "dimension": "检查",
        "when_to_use": "",
        "why_effective": "",
        "boundaries": "不猜测作者的排版检查程序",
        "mini_exercise": "待补充：不猜测作者的排版检查程序",
        "executable": False,
    },
    {
        "id": "EP-CW-026",
        "title": "用颜色辅助检查文章是否清爽",
        "chapter": "打磨表达",
        "method_type": "training",
        "dimension": "检查",
        "when_to_use": "",
        "why_effective": "",
        "boundaries": "不猜测颜色含义与判断阈值",
        "mini_exercise": "待补充：不猜测颜色含义与判断阈值",
        "executable": False,
    },
    {
        "id": "EP-CW-027",
        "title": "让开头与结尾相互呼应",
        "chapter": "打磨表达",
        "method_type": "technique",
        "dimension": "结构",
        "when_to_use": "想让文章有闭合感时",
        "why_effective": "首尾呼应给读者「走完一圈」的完整感",
        "boundaries": "呼应须自然，不为了闭合生硬拉回开头",
        "mini_exercise": "让结尾回应开头的问题或意象，检查是否生硬",
        "executable": True,
    },
    {
        "id": "EP-CW-028",
        "title": "恰当地使用引号",
        "chapter": "打磨表达",
        "method_type": "technique",
        "dimension": "标点",
        "when_to_use": "引用、术语或强调容易混淆时",
        "why_effective": "引号用法清晰，减少误读",
        "boundaries": "区分真实引用、术语与强调，检查误导风险",
        "mini_exercise": "区分真实引用、术语与强调，检查误导风险",
        "executable": True,
    },
    {
        "id": "EP-CW-029",
        "title": "通过精简改善节奏",
        "chapter": "打磨表达",
        "method_type": "technique",
        "dimension": "节奏",
        "when_to_use": "句子拖沓、读起来没有力度时",
        "why_effective": "删冗余后停顿与力度更清晰",
        "boundaries": "精简不是统一规则，可能损失必要的铺垫",
        "mini_exercise": "删去一句中的冗余，再朗读比较停顿与力度",
        "executable": True,
    },
    {
        "id": "EP-CW-030",
        "title": "边写边朗读",
        "chapter": "打磨表达",
        "method_type": "training",
        "dimension": "节奏",
        "when_to_use": "想检查句子顺不顺时",
        "why_effective": "朗读暴露拗口与换气困难",
        "boundaries": "朗读是检查手段，不保证读者同感",
        "mini_exercise": "朗读用户写的一段，标出拗口或换气困难的位置",
        "executable": True,
    },
    {
        "id": "EP-CW-031",
        "title": "用问答引导读者思考",
        "chapter": "打磨表达",
        "method_type": "technique",
        "dimension": "手法",
        "when_to_use": "想让读者跟着一个问题走时",
        "why_effective": "一个好问题牵引读者主动想",
        "boundaries": "不设空泛设问；问题须与核心相关",
        "mini_exercise": "设置一个与核心问题有关的问答，不用空泛设问",
        "executable": True,
    },
    {
        "id": "EP-CW-032",
        "title": "警惕复制粘贴带来的问题",
        "chapter": "打磨表达",
        "method_type": "scenario",
        "dimension": "修订",
        "when_to_use": "文章含粘贴段落时",
        "why_effective": "检查粘贴处，避免来源/重复/口吻不一致",
        "boundaries": "检查来源、语境、重复与口吻一致性，不照单全收",
        "mini_exercise": "检查粘贴部分的来源、语境、重复与口吻一致性",
        "executable": True,
    },
    {
        "id": "EP-CW-033",
        "title": "练习记笔记",
        "chapter": "日常训练",
        "method_type": "training",
        "dimension": "积累",
        "when_to_use": "想建立素材积累习惯时",
        "why_effective": "记录观察与情境，日后可复用",
        "boundaries": "须记触发情境，不孤立记一句",
        "mini_exercise": "记录一个观察及触发它的具体情境",
        "executable": True,
    },
    {
        "id": "EP-CW-034",
        "title": "通过给人指路，练习概括与说明",
        "chapter": "日常训练",
        "method_type": "training",
        "dimension": "说明",
        "when_to_use": "想练清晰说明时",
        "why_effective": "指路要求按序、无遗漏地说明",
        "boundaries": "检查遗漏，不假设对方已知道",
        "mini_exercise": "为一个具体目的地写简短指路说明，检查遗漏",
        "executable": True,
    },
    {
        "id": "EP-CW-035",
        "title": "抄写小学数学题",
        "chapter": "日常训练",
        "method_type": "training",
        "dimension": "说明",
        "when_to_use": "",
        "why_effective": "",
        "boundaries": "不推断作者的训练机制或评判标准",
        "mini_exercise": "待补充：不推断作者的训练机制或评判标准",
        "executable": False,
    },
    {
        "id": "EP-CW-036",
        "title": "充分输出所学内容",
        "chapter": "日常训练",
        "method_type": "training",
        "dimension": "迁移",
        "when_to_use": "学到一个方法想真正会用时",
        "why_effective": "用自己的素材应用，检验是否真的掌握",
        "boundaries": "须用自己素材，不照抄原例",
        "mini_exercise": "用自己的素材写出一个所学方法的应用",
        "executable": True,
    },
    {
        "id": "EP-CW-037",
        "title": "建立自己的名言笔记",
        "chapter": "日常训练",
        "method_type": "training",
        "dimension": "积累",
        "when_to_use": "想积累值得记住的表达时",
        "why_effective": "记录原句、来源与理解，日后可引用",
        "boundaries": "核实引用，不凭记忆转述",
        "mini_exercise": "记录原句、来源和自己的理解，核实引用",
        "executable": True,
    },
    {
        "id": "EP-CW-038",
        "title": "从广播中留意并积累表达",
        "chapter": "日常训练",
        "method_type": "training",
        "dimension": "积累",
        "when_to_use": "想积累口语化表达时",
        "why_effective": "广播里有自然的说话方式",
        "boundaries": "记语境与来源，不脱离语境套用",
        "mini_exercise": "记下一个喜欢的表达及其语境和来源",
        "executable": True,
    },
    {
        "id": "EP-CW-039",
        "title": "在较短时间内集中写作",
        "chapter": "日常训练",
        "method_type": "training",
        "dimension": "习惯",
        "when_to_use": "想练短时间完成一段时",
        "why_effective": "短时限减少拖延，逼出初稿",
        "boundaries": "5–10 分钟段落练习，不强制延长会话",
        "mini_exercise": "安排5–10分钟段落练习，不强制延长会话",
        "executable": True,
    },
    {
        "id": "EP-CW-040",
        "title": "写提案时，预想实际展示方案的场景",
        "chapter": "按场景写",
        "method_type": "scenario",
        "dimension": "提案",
        "when_to_use": "写提案、需要推动一个决定时",
        "why_effective": "想象展示对象与决定，检查信息是否足够",
        "boundaries": "聚焦对象需要做的决定，不堆无关背景",
        "mini_exercise": "想象展示对象与需要作出的决定，检查信息是否足够",
        "executable": True,
    },
    {
        "id": "EP-CW-041",
        "title": "写求职材料时，考虑自己与企业的契合点",
        "chapter": "按场景写",
        "method_type": "scenario",
        "dimension": "求职",
        "when_to_use": "写求职材料时",
        "why_effective": "真实经历对上岗位要求，更有说服力",
        "boundaries": "将真实经历对应岗位要求，不补造资历",
        "mini_exercise": "将真实经历对应岗位要求，不补造资历",
        "executable": True,
    },
    {
        "id": "EP-CW-042",
        "title": "用四段结构组织书信",
        "chapter": "按场景写",
        "method_type": "technique",
        "dimension": "书信",
        "when_to_use": "",
        "why_effective": "",
        "boundaries": "不猜测四段分别承担什么功能",
        "mini_exercise": "待补充：不猜测四段分别承担什么功能",
        "executable": False,
    },
    {
        "id": "EP-CW-043",
        "title": "认识到道歉信有表达上的局限",
        "chapter": "按场景写",
        "method_type": "scenario",
        "dimension": "道歉",
        "when_to_use": "",
        "why_effective": "",
        "boundaries": "不声称某种文字能保证获得谅解",
        "mini_exercise": "待补充作者论述；不声称某种文字能保证获得谅解",
        "executable": False,
    },
    {
        "id": "EP-CW-044",
        "title": "写感谢信时，呈现具体情景",
        "chapter": "按场景写",
        "method_type": "scenario",
        "dimension": "感谢",
        "when_to_use": "写感谢信时",
        "why_effective": "具体情景让感谢可信、不空泛",
        "boundaries": "写明对方做了什么及带来的具体帮助",
        "mini_exercise": "写明对方做了什么及带来的具体帮助",
        "executable": True,
    },
    {
        "id": "EP-CW-045",
        "title": "写工作邮件时，优先处理工作信息",
        "chapter": "按场景写",
        "method_type": "scenario",
        "dimension": "邮件",
        "when_to_use": "写工作邮件时",
        "why_effective": "事项与动作靠前，降低沟通成本",
        "boundaries": "明确事项、所需动作与必要时间信息",
        "mini_exercise": "明确事项、所需动作与必要时间信息",
        "executable": True,
    },
    {
        "id": "EP-CW-046",
        "title": "写社交媒体内容时，表达真实感受，并面向具体的人",
        "chapter": "按场景写",
        "method_type": "scenario",
        "dimension": "社交媒体",
        "when_to_use": "写社交媒体内容时",
        "why_effective": "面向具体的人、保留真实感受，更像真实表达",
        "boundaries": "选定具体读者，保留真实感受，不编造经历",
        "mini_exercise": "选定具体读者，保留真实感受，不编造经历",
        "executable": True,
    },
    {
        "id": "EP-CW-047",
        "title": "写广告文案时，选择能打动特定对象的语言",
        "chapter": "按场景写",
        "method_type": "scenario",
        "dimension": "广告",
        "when_to_use": "写广告文案时",
        "why_effective": "围绕对象的具体需求，更有针对性",
        "boundaries": "围绕对象的具体需求组织措辞，效果主张须有依据",
        "mini_exercise": "围绕对象的具体需求组织措辞，效果主张须有依据",
        "executable": True,
    },
    {
        "id": "EP-CW-048",
        "title": "工作写作避免过度追求完美",
        "chapter": "按场景写",
        "method_type": "scenario",
        "dimension": "工作",
        "when_to_use": "工作写作纠结于完美、迟迟不交付时",
        "why_effective": "明确充分标准，能按时交付",
        "boundaries": "确定当前交付的充分标准，完成一轮修订即可收束",
        "mini_exercise": "确定当前交付的充分标准，完成一轮修订即可收束",
        "executable": True,
    },
]
