"""add draft versions and critic reports

Revision ID: 07a1d0830293
Revises: 83df888a7838
Create Date: 2026-09-03 14:00:14.029481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '07a1d0830293'
down_revision: Union[str, None] = '83df888a7838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criticreportrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('criticreportrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criticreportrecord_draft_id'), ['draft_id'], unique=False)

    op.create_table('draftversionrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draftversionrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draftversionrecord_draft_id'), ['draft_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draftversionrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draftversionrecord_draft_id'))

    op.drop_table('draftversionrecord')
    with op.batch_alter_table('criticreportrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criticreportrecord_draft_id'))

    op.drop_table('criticreportrecord')
    # ### end Alembic commands ###
