"""baseline schema

Revision ID: 83df888a7838
Revises: 
Create Date: 2026-09-03 13:59:07.282784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83df888a7838'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentjobrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draftrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidencecardrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidencecardrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidencecardrecord_event_id'), ['event_id'], unique=False)

    op.create_table('feedbackrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noderecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('noderecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_noderecord_run_id'), ['run_id'], unique=False)

    op.create_table('reviewhistoryrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviewhistoryrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviewhistoryrecord_draft_id'), ['draft_id'], unique=False)

    op.create_table('reviewrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviewrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviewrecord_draft_id'), ['draft_id'], unique=False)

    op.create_table('runrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runrecord')
    with op.batch_alter_table('reviewrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviewrecord_draft_id'))

    op.drop_table('reviewrecord')
    with op.batch_alter_table('reviewhistoryrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviewhistoryrecord_draft_id'))

    op.drop_table('reviewhistoryrecord')
    with op.batch_alter_table('noderecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_noderecord_run_id'))

    op.drop_table('noderecord')
    op.drop_table('feedbackrecord')
    with op.batch_alter_table('evidencecardrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidencecardrecord_event_id'))

    op.drop_table('evidencecardrecord')
    op.drop_table('draftrecord')
    op.drop_table('contentjobrecord')
    # ### end Alembic commands ###
